name: Deploy Peer 2 Peer People

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: git pull, build and deploy
      if: github.event.commits[0].message != 'synch'
      run: |
        echo geil,
        sshpass -p ${{ secrets.pw }} ssh root@78.47.72.72 -o StrictHostKeyChecking=no < ./deploy.bash
